export { default as Home } from './home/Home'
export { default as Product } from './product/Product'
export { default as Sales } from './sales/Sales'
export { default as Offers } from './offers/Offers'
export { default as Auth } from './auth/Auth'
export { default as Edit } from './edit/Edit'
export { default as Add } from './addProduct/Add'
