name: Deployment Heroku DEV STAGE (base)

on:
  pull_request:
    paths: 
      - 'backend/**'
    branches:
      - develop
    types: [closed]

jobs:
  deploy_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy from base_ref
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.DEV_HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.DEV_HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.DEV_HEROKU_EMAIL}}
          branch: ${{ format('origin/{0}', github.base_ref) }}
          appdir: backend
