name: Deployment Heroku DEV STAGE

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy_base:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ format('origin/{0}', github.base_ref) }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build frontend & copy to backend public
        working-directory: ./frontend
        run: |
          yarn install
          yarn build
          cp -av ./build/. ../backend/public/
      - name: Tidy backend public folder
        working-directory: ./backend
        run: |
          mv -v ./public/static/. ./public/
          mv -v ./public/index.html ./views/
      - name: Commit changes
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github.action@users.noreply.github.com'
          git commit -am "Automated commit (base-dev)"
          git push origin ${{ format('origin/{0}', github.base_ref) }}
      - name: deploy from base_ref
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.DEV_HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.DEV_HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.DEV_HEROKU_EMAIL}}
          branch: ${{ format('origin/{0}', github.base_ref) }}
          appdir: backend
  deploy_head:
    runs-on: ubuntu-latest
    if: github.event.action == 'synchronize' || github.event.action == 'reopened' || github.event.action == 'opened'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ format('origin/{0}', github.head_ref) }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build frontend & copy to backend public
        working-directory: ./frontend
        run: |
          yarn install
          yarn build
          cp -av ./build/. ../backend/public/
      - name: Tidy backend public folder
        working-directory: ./backend
        run: |
          mv -v ./public/static/. ./public/
          mv -v ./public/index.html ./views/
      - name: Commit changes
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'github.action@users.noreply.github.com'
          git commit -am "Automated commit (head-dev)"
          git push origin ${{ format('origin/{0}', github.head_ref) }}
      - name: deploy from head_ref
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.DEV_HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.DEV_HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.DEV_HEROKU_EMAIL}}
          branch: ${{ format('origin/{0}', github.head_ref) }}
          appdir: backend
